### PR TITLE
Harmonized argument with what is written in USAGE.md

### PR DESCRIPTION
**Pull request by m000**

### CODE REVIEW

**Comment by moyix** [comment]
Any chance we could change the documentation instead? We have some scripts that have the `no_tp` syntax baked in.

**Comment by m000** [comment]
Sure. I'll make a new pull request.

2016-07-29 4:10 GMT+02:00 Brendan Dolan-Gavitt <notifications@github.com>:

**Comment by m000** [comment]
I updated README.md for the specific argument.

From a quick look, taint2/README.md is written for the old taint plugin and needs a more thorough cleanup.

**Comment by m000** [comment]
I updated README.md for the specific argument. From a quick look, taint2/README.md is written for the old taint plugin and needs a more thorough cleanup.

I also changed the boolean plugin argument parsing, so that "0" is parsed to false.

**Pull request merged**
